### ISSUE TITLE
Reusable apps shouldn't swap the user model

### ISSUE THREAD

**Issue by febsn** [jrief/django-shop#11]
At the moment, django-shop requires swapping in a customized user model. This is not recommended for reusable apps (see https://docs.djangoproject.com/en/dev/topics/auth/customizing/#extending-user).

I suggest creating a separate Customer model that carries all shop-specific data with a nullable OneToOne relationship to the user model. I'll write some tests to demonstrate the functionality and for discussion.

First and foremost: Should I design this for the current deferred model architecture, or already switch to django-swappable models? What are your thoughts?

**Comment by rfleschenberg** [comment]
This issue was moved to awesto/django-shop#319
