### ISSUE TITLE
customer context processor breaks aldryn-search indexing

### ISSUE THREAD

**Issue by febsn** [jrief/django-shop#18]
The customer context processor raises an error when trying to update the `aldryn-search` index, because, apparently, `aldryn-search` doesn't emulate middleware behaviour:
```AssertionError: The request object does not contain a customer. Edit your MIDDLEWARE_CLASSES setting to insert 'shop.middlerware.CustomerMiddleware'.```
Creating separate settings for index creation/update without the `customer` context processor enabled and setting `search_fulltext = False` on `shop.cascade.plugin_base.ShopPluginBase` works as a workaround. Customer-specific data should obviously not be included in a search index anyway, but there might be also plugins with output suitable for indexing, so this solution is probably not fine-grained enough.

**Comment by jrief** [comment]
I never used aldryn search, so I can't any advise on that. I'm just wondering why you can't add some additional middleware classes to your project.

Please note that django-shop uses haystack and drf-haystack and is shipped with full-text indexing support.

**Comment by febsn** [comment]
aldryn-search is an additional layer for haystack which automatically indexes django-cms plugins' contents. I haven't digged deeper, but I suppose that it emulates requests in order to do that, which fails for reasons described above.
I do see this as a potential problem as django-shop is tightly coupled to django-cms and aldryn-search is the de-facto standard for cms page indexing.

**Comment by rfleschenberg** [comment]
This issue was moved to awesto/django-shop#318
