### ISSUE TITLE
CustomerProxy breaks django-CMS user admin

### ISSUE THREAD

**Issue by febsn** [jrief/django-shop#20]
The Proxy Model approach in shop.admin.customer leads to following error for me:
```
FieldError at /de/admin/cms/pageuser/2/

Unknown field(s) (last_access, recognized) specified for PageUser. Check fields/fieldsets/exclude attributes of class PageUserAdmin.
```

Steps to reproduce: Access a customer in the shop section of the admin (saving not necessary), then try to access a page user in the CMS section.
Generally, the current admin implementation assumes that all Users have an associated Customer, which isn't necessarily true. This makes integrating django-shop into an existing django-CMS project harder.
Edit to clarify: It seems that Django can't handle double-registration of a model via a proxy podel; as far as I can tell, it tries to use the CustomerAdmin also for PageUser objects after CustomerAdmin has once been called.
Maybe I'm just making a mistake registering the CustomerAdmin; how is that to be done? (Is it included in the example project?)

**Comment by jrief** [comment]
These two fields have been introduced recently. Currently they are available on this branch
https://github.com/jrief/django-shop/blob/0.3.0.dev/shop/models/customer.py

May it be that you forgot to rebase your branch against mine?

**Comment by febsn** [comment]
Accessing the CustomerAdmin works, it's not about the fields not being existant in the model; mocking them for the User model in the admin seems to be the cause.
The problem is that django apparently tries to use the CustomerAdmin — or parts of it, to be exact, as the methods don't seem to be accessed — for displaying the PageUser changelist of django-cms. I haven't digged into how the django admin registration works, but it has to do with that.

**Comment by jrief** [comment]
OK, thanks for reporting.
You have Users without associated Customer object, do you?
Then, according to my first check, some of the code can not work properly.
I'll fix that.

**Comment by jrief** [comment]
I now tested locally. The latest patch fixes this issue.
