### ISSUE TITLE
Breaking News on the new django-shop

### ISSUE THREAD

**Issue by jrief** [jrief/django-shop#25]
Today, as of 2015-12-05, I finally finished three demos which should run out of the box.

Please read the files ``docs/tutorial/intro.rst`` and ``docs/tutorial/quickstart.rst``. Following
the instructions should create a running shop in minutes. You can even pay by credit card, if you
apply for your own testing account at Stripe.

I would be happy to hear some feedback.

**Comment by vivazzi** [comment]
Thank you! This is great work! Early I try to run on django 1.8.4, but I get error with incompatible versions of cascade plugins. Now I try use your requirements in demo.

And I think it is better don't bind shop plugins with cascade-bootstrap? how do you think? It would allow install django shop without cascade

**Comment by jrief** [comment]
The demo requires djangocms-cascade. This is because the product list-views, the cart, the checkout and the order views are implemented using pure djangoCMS pages. Therefore I need these plugins.

Whoever does not like djangocms-cascade may implement all those templates by hand, **djangoSHOP** will perfectly accept that. But that's out of the scope of this demo.

**Comment by vivazzi** [comment]
I'm sorry for my inaccuracy. That's right - djangocms-cascade is need. I see the strong binding between djangocms-bootstrap3 and django-shop in the declaration of parent_classes in Plugins. For example:
```
class ShopCatalogPlugin(ShopPluginBase):
    name = _("Catalog List Views")
    require_parent = True
    parent_classes = ('BootstrapColumnPlugin',)
```
May be it is better remove parent_classes?

**Comment by jrief** [comment]
You're right. Of course it would be better the declare  the ``ShopCatalogPlugin`` as a child of a generic Column Plugin, not only a ``BootstrapColumnPlugin ``. Valid point! Will think about it.

Bit you can run django-shop without any Cascade plugins altogether, if you write the templates by hand.

**Comment by Mohl** [comment]
I just pulled the project and worked my way through intro.rst and quikstart.rst, but i had to re-run ./manage.py makemigrations in order to get the fixtures to load - you might want to double-check this :-)

**Comment by Mohl** [comment]
I also had to run
sudo apt-get install nodejs-legacy
on Ubuntu 14.04. I previously skipped that step and wondered why the javascript wasn't working - apparently, the legacy package is required for bower to set up the statics correctly.

**Comment by rfleschenberg** [comment]
I can confirm that you need to install ``nodejs-legacy`` on Ubuntu 14.04. Also, it seems that you need to run the ``npm install`` step as root?

However, I am not sure if we want to document such distribution-specific instructions. Then again, Ubuntu 14.04 might be a good distribution to pick as an example for the documentation.

**Comment by jrief** [comment]
We made a version jump to 0.9, because of so many changes.
