### ISSUE TITLE
Differences with Django Polymorphic?

### ISSUE THREAD

**Issue by cyberjoac** [jrief/django-shop#3]
I'm trying to understand the difference between django-polymorphic and DeferredForeignKey?
From my understanding, you refactored the code using DeferredForeignKey, DeferredOneToOneField etc..., while previously it was using django-polymorphic?
It seems conceptually similar to me, and I'd be happy to understand it a bit better...

What are the pros and cons of each approach?

Thanks.

**Comment by jrief** [comment]
django-shop uses django-polymorphic in combination with deferred foreign keys. Its not a question what is better. The deferred pattern is explained in here: http://django-shop.readthedocs.org/en/latest/reference/deferred-models.html

**Comment by rfleschenberg** [comment]
This issue was moved to awesto/django-shop#320
