### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by rfleschenberg** [jrief/django-shop#41]
We don't support Django 1.9 yet. We should investigate what is necessary to change that.

I will do that sooner or later, but any help is welcome, of course.

**Comment by jrief** [comment]
as soon as django-cms supports Django-1.9 I'll attempt a migration.

**Comment by rfleschenberg** [comment]
Closing this -- I think we have it on our radar anyway, and can track it in the Awesto repository :)
