### ISSUE TITLE
may be add 'recursive-include static *' to MANIFEST.in

### ISSUE THREAD

**Issue by vivazzi** [jrief/django-shop#52]
I'm not sure, but may be add 'recursive-include static *' to MANIFEST.in?
I try to integrate shango-shop to existing project and I get error 'Unable to locate file shop/css/navbar.scss while rendering template'.

**Comment by rfleschenberg** [comment]
Hello vivazzi, and thank you for the report. Can you please give us a short description of the exact steps to reproduce your issue?

**Comment by vivazzi** [comment]
Hello rfleschenberg, if short: I integrated django-shop to existing project:
1. added requirements from 'django-shop/requirements/django18/common.txt' and added 'git+https://github.com/jrief/django-shop.git' to my requirements.txt
2. added example app from 'django-shop' to my project.
3. compiled node_modules and bower_components
4. writed and check paths to node_modules and bower_components in settings.py

I hope I don't miss anything.
I write post about integrate django-shop to existing project which consist more details (though in Russian). May be I write in English. Although it a little difficult for me.
And one question: I want to add Russian translate of django-shop. How I can it? pull-request or transifex.com?

**Comment by rfleschenberg** [comment]
Thanks, vivazzi. We will have a look at this ASAP.

**Comment by rfleschenberg** [comment]
For translation, please just send a pull request with a po file. Maybe we should look at Transifex for the future, thanks for suggesting this!

**Comment by vivazzi** [comment]
Thank you! I try to take part in development of django-shop. My thought I will write later

**Comment by jrief** [comment]
The MANIFEST.in file has been fixed now. It inherited from the old version of django-shop and hence many years old.

**Comment by rfleschenberg** [comment]
Closing as fixed.
