### ISSUE TITLE
Add example shop for sale of digital goods

### ISSUE THREAD

**Issue by vivazzi** [jrief/django-shop#53]
Could you help, please! Your example is very good but they are not for sale of digital goods (e-product).  How I think:
- product-add2cart.html does not consist of the changing 'Quantity'. Typically, the customer buys only one copy of e-product.
- we don't need ask customer shipping and billing address. So it unless info.

What do you think about it?

**Comment by jrief** [comment]
> product-add2cart.html does not consist of the changing 'Quantity'. Typically, the customer buys only one copy of e-product.

yes, that's perfectly valid. The quantity then can be considered as a boolean value. Currently the quantity can be an integer, a decimal and a float. Something debatable would be to also allow booleans, but since in the database they are stored as integers, I left them out.

> we don't need ask customer shipping and billing address. So it unless info.

You don't need them anyway. You then can even skip the shipping method. But its just as easy as removing those form-plugins from the tree-editor. Have you tried that out?

**Comment by vivazzi** [comment]
My attempt to start the application in process. I have some problem... For example, with sending of email after successful stripe payment. Or with using command rebuild_index --noinput (if I don't soved it I write about it). Therefore I have run my app! May be my problems is my English when I read docs :)

**Comment by jrief** [comment]
Did you setup the email templates and the notifications as described in the docs?

**Comment by vivazzi** [comment]
I will setup notification later, because I can not add button "Buy" instead of import {% include "myshop/catalog/product-add2cart.html" %}, because e-product doesn't need change Quantity. I spent whole day to add button "Buy", but It seems that without knowlenge of angular and rest framework I can not do it

**Comment by vivazzi** [comment]
I find my bug. It was so stupid! I forgot to add csrf_token to my ajax post.

**Comment by jrief** [comment]
Thanks for informing me.
Would you like to share this demo shop?

**Comment by vivazzi** [comment]
I'd like to share but now It has no interest, because I don't finish my work. Periodically I get some problems with usage of django-shop and half of them I solved. I have some issues which I didn't write here yet, because I think about as to formulate them and how I can in solved them. 
Django shop is great work! I try to help you as I can!

**Comment by rfleschenberg** [comment]
Thank you, @vivazzi! Feel free to open a new issue if you run into any problems.
