### ISSUE TITLE
Is there an easy instructed way to setup a DjangoShop from a new System ?

### ISSUE THREAD

**Issue by klausz** [jrief/django-shop#54]
I am not that experienced and tried to use:
(1) Debian 64 bit 8.3 minimal (Hetzner).
(2) Raspbian on a Raspberry PI. (Raspbian, if possible would be tye preferred future solution). The third try was 
(3) to enhance an new downloaded existing Django Virtual Machine from Turnkeylinux.org.
Basically i used the instructions for the three different test shops. 

I could enter the commands I used later today into the Wiki if this is welcome.

Finally I would like to have an operative Webshop selling roughly 5 diffent products from Germany within Europe.

Maybe i should not ask here, but where?

**Comment by jrief** [comment]
This sounds like a typical support case.
Can you please contact me by email or Google Hangout.

**Comment by jrief** [comment]
Btw. if you only have to sell five products, its probably better to just declare a simple product with a placeholder and fill that using the Cascade ecosystem.
