### ISSUE TITLE
Remove requirements: django-filer, easy_thumbnails

### ISSUE THREAD

**Issue by vivazzi** [jrief/django-shop#56]
django-filer and easy_thumbnails is beautiful libraries but I have another logic of load of pictures. And I don't need django-filer and easy_thumbnails. But I cannot remove them because NotificationAttachment has attachment = FilerFileField(...) in shop/models/notification.py. My trying of fix this moment is fail. 
I think code should look like that:
```
try:
    from filer.fields.file import FilerFileField
except ImportError:
    from django.db.models import FileField as FilerFileField
```
I get error.

Also I tried to emulate FilerFileField, but I get error..

I will glad for help me!

**Comment by jrief** [comment]
django-filer and easythumbnails are also required by djangocms-cascade and
by django-cms.
Therefore removing them will disable much more of that framework.


2016-02-25 0:37 GMT+01:00 Maltsev Artyom <notifications@github.com>:

**Comment by vivazzi** [comment]
Okay, if there are many usage.. I just want to use more light version of django-shop for my shop without many requirements.

**Comment by rfleschenberg** [comment]
As Jacob has said, django-shop currently depends on django-cms and djangocms-cascade. If you want to use a version with fewer dependencies, you will probably have to fork django-shop -- sorry. In the future, maybe we can investigate how to make some dependencies optional, but that is not a focus of our work right now.

However, you can probably still implement your own logic for picture loading. You just need to find the right bits to override. Feel free to contact me directly if you need some advice on this. I am usually on IRC in `#django-shop` (nickname `moldy`), or you can send me an e-mail: `rene@fleschenberg.net`.

If you run into any other issues with django-shop, I suggest that you open an issue here: https://github.com/awesto/django-shop/ 

It's easier for us if we keep all issues in one repository. Thanks!
