### ISSUE TITLE
use django.utils.timezone instead of datetime

### ISSUE THREAD

**Issue by jrief** [jrief/django-shop#60]

**Comment by khchine5** [comment]
Hi @jrief , could I help with this issue ?

**Comment by jrief** [comment]
If you want to do it, please go ahead with pleasure.

**Comment by khchine5** [comment]
Thanks.
Should I add timezone selection in the register user form ?

**Comment by jrief** [comment]
Django projects should run in UTC internally. Only for the representation it is important to use the timezone depending on the Customers settings, which will currently do not have yet, but might be added using the customers location. For for now, the TZ settings is enough.

**Comment by rfleschenberg** [comment]
I am closing this issue because I am merging @khchine5's fixes in https://github.com/awesto/django-shop/pull/375. Thanks!
