### ISSUE TITLE
Tutorial to deployment with nginx 

### ISSUE THREAD

**Issue by alexvechirko** [jrief/django-shop#75]
It will be nice if we had a script or tutorial to serve application with Nginx server

**Comment by rfleschenberg** [comment]
I agree, but this is more a generic Django issue than a djangoSHOP-specific one.

I am planning to write an article about this and possibly publish my Ansible playbook for this, but I don't know when I will find the time to do this. Meanwhile, here are some related resources:

nginx with uwsgi::

* https://docs.djangoproject.com/en/1.10/howto/deployment/wsgi/uwsgi/
* http://musings.tinbrain.net/django-deploy/
* http://uwsgi-docs.readthedocs.io/en/latest/tutorials/Django_and_nginx.html

nginx with gunicorn:
* https://docs.djangoproject.com/en/1.10/howto/deployment/wsgi/gunicorn/
* http://docs.gunicorn.org/en/stable/deploy.html

**Comment by alexvechirko** [comment]
@rfleschenberg thank's
